version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12
      nodejs: 10
    commands:
      - npm i -g yarn
      - yarn install
      - echo Deploying website
  build:
    commands:
      - yarn build && aws s3 sync --delete build "s3://xiaoyongxu.com"
cache:
  paths:
      - node_modules/**/*
      - public/**/*
      - /u